chain_width = 100
comment_width = 100
fn_call_width = 100
format_code_in_doc_comments = true
hex_literal_case = "Upper"
match_block_trailing_comma = true
max_width = 100
# tab_spaces = 2
# use_small_heuristics="Default"
